### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghost** [zeopticz/zcb-2.0#10]
Clicks: Kawaii's Clicks
Soft Click Delay: 50ms
Macro:
Level: The Golden
FPS: 60
Actions: 710

Error code:
-----------------------------------------------------------------------
[-] ERROR: An Error occured while generating clicks!
If the issue persists, please contact support!
Error: Traceback (most recent call last):
  File "zcb.py", line 99, in <module>
  File "utils.py", line 386, in generate_clicks
  File "pydub\audio_segment.py", line 468, in silent
OverflowError: cannot fit 'int' into an index-sized integer
-----------------------------------------------------------------------

Oh yeah I converted this macro from ZBot Frame.

**Comment by zeopticz** [comment]
steps to reproduce?
