### ISSUE TITLE
help mee

### ISSUE THREAD

**Issue by venten9** [zeopticz/zcb-2.0#11]
![image](https://user-images.githubusercontent.com/111290529/184642782-ffa3ca19-a6c3-49cb-b640-bec66e524ed1.png)

**Comment by venten9** [comment]
[i] INFO: File: "C:/Users/User/Desktop/zcb/hause.echo"
[i] INFO: FPS: 360
[i] INFO: Actions: 0

Softclick Delay (In MS, Leave blank for default value) >
[-] ERROR: An Error occured while generating clicks!
If the issue persists, please contact support!
Error: Traceback (most recent call last):
  File "utils.py", line 396, in generate_clicks
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "zcb.py", line 116, in <module>
  File "utils.py", line 398, in generate_clicks
IndexError: list index out of range

**Comment by dekrypted** [comment]
Are you using a binary echo macro?

**Comment by venten9** [comment]
> 
i convert mhr.json to echo

**Comment by dekrypted** [comment]
frame based... right?

**Comment by zeopticz** [comment]
use zcb 3: https://github.com/zeozeozeo/zcb3/releases/
