### ISSUE TITLE
MH Replay support?

### ISSUE THREAD

**Issue by x8c8r** [zeopticz/zcb-2.0#13]
Since Mega Hack Replay is literally built-in megahack v7 which most people have, I think it will make sense to add support for it's macros in future.

**Comment by EESports7** [comment]
here is a version that has support
[https://github.com/Ploosho/zcb-2.0/releases/tag/v1.3.1-zbot-mhr](url)

**Comment by dekrypted** [comment]
This feature is in development, thanks!

**Comment by zeopticz** [comment]
use zcb 3: https://github.com/zeozeozeo/zcb3/releases/
