### ISSUE TITLE
KeyError: 'fps' on ZCB v2

### ISSUE THREAD

**Issue by LinkOnIt** [zeopticz/zcb-2.0#15]
It keeps giving me this exact output when I try to generate clicks for my MHR JSON macro, Can someone please help me? 

[i] INFO: Parsing File: C:/Users/user/Documents/Steam/steamapps/common/Geometry Dash/macros/Slaughterhouse.mhr.json
[-] ERROR: An Error occured while parsing replay!
If the issue persists, please contact support!
Error: Traceback (most recent call last):
  File "zcb.py", line 66, in <module>
  File "utils.py", line 111, in parse_tasbot
KeyError: 'fps'

**Comment by zeopticz** [comment]
use zcb 3: https://github.com/zeozeozeo/zcb3/releases/
