### ISSUE TITLE
How do I download the gui

### ISSUE THREAD

**Issue by RattyLogs** [zeopticz/zcb-2.0#17]
WHY CANT ANYONE SAY HOW TO DOWNLOAD THE GUI LIKE WHY I JUST WANT CLICKS FOR MY GD BOT WHY WHY WHY

**Comment by zeozeozeo** [comment]
zcb 2.0 has no gui. zcb 3 has it, i'll probably release it tomorrow

**Comment by zeopticz** [comment]
zcb 2.0 has no gui. zcb 3 has it, i'll probably release it tomorrow

**Comment by zeopticz** [comment]
![image](https://github.com/zeopticz/zcb-2.0/assets/60877577/9c216c11-d672-4569-bea9-ef865ebf0f43)

**Comment by zeopticz** [comment]
use zcb 3: https://github.com/zeozeozeo/zcb3/releases/
