### ISSUE TITLE
I need 32 bit version of ZCB.

### ISSUE THREAD

**Issue by ghost** [zeopticz/zcb-2.0#3]
Please compile 32 bit version of ZCB. At least the 2.0.

**Comment by zeopticz** [comment]
It's not this simple when you're using Pyinstaller. How about you try to run it from source? `python zcb.py`
Python is cross-platform

**Comment by ghost** [comment]
You know what? Okay You can't compile 32 bit using Python. It was just a question.

**Comment by zeopticz** [comment]
> You know what? Okay You can't compile 32 bit using Python. It was just a question.

You can

**Comment by ghost** [comment]
how?

**Comment by zeopticz** [comment]
> how?

you can use 32-bit python

**Comment by ghost** [comment]
Well I have zero knowledge of Python.

**Comment by zeopticz** [comment]
> Well I have zero knowledge of Python.

use pyinstaller with 32 bit python

**Comment by user100056** [comment]
link?

**Comment by ghost** [comment]
Why you cant compile 32 bit using Python? Also is there even something called 64 bit to 32 bit exe?

**Comment by zeopticz** [comment]
> Why you cant compile 32 bit using Python? Also is there even something called 64 bit to 32 bit exe?

no, the python website has 32 bit and 64 bit downloads
you can't run 64 bit python on a 32 bit platform

**Comment by ghost** [comment]
i need pyinstaller

**Comment by ghost** [comment]
nah i give up

**Comment by ghost** [comment]
Why you cant just use pyinstaller?

**Comment by ghost** [comment]
bruh

**Comment by zeopticz** [comment]
> Why you cant just use pyinstaller?

That's what I'm suggesting you to do, except use the 32-bit python to run it

**Comment by user100056** [comment]
Well because it to complicated. then why you can't download 32 bit yourself?

**Comment by user100056** [comment]
is t

**Comment by ghost** [comment]
pls do tutorial on how to compile it

**Comment by ghost** [comment]
pls!

**Comment by user100056** [comment]
i wont come back if you show tutorial ( ͡° ͜ʖ ͡°)

**Comment by zeopticz** [comment]
> Well because its to complicated. then why you can't download 32 bit yourself?

currently, github actions packages the exe's. the job i use produces 64 bit EXE's. I don't build anything on my machine

**Comment by zeopticz** [comment]
> pls do tutorial on how to compile it

search up "using pyinstaller with python"

**Comment by zeopticz** [comment]
> i need pyinstaller

install it using your package manager.

**Comment by ghost** [comment]
ok i think im just making you angry sorry lol

**Comment by zeopticz** [comment]
> ok i think im just making you angry sorry lol

I'm not angry

**Comment by ghost** [comment]
that was a joke lol

**Comment by ghost** [comment]
OH CMON!

**Comment by zeopticz** [comment]
what?

**Comment by zeopticz** [comment]
is this still not solved?

**Comment by ghost** [comment]
no

**Comment by ghost** [comment]
im downloading and installing Python

**Comment by ghost** [comment]
version 3.9.6

**Comment by ghost** [comment]
oh yea
do i need to "Add Python to PATH"?

**Comment by ghost** [comment]
i selected to add it its installed now what?

**Comment by ghost** [comment]
YES I COMPILED IT

**Comment by ghost** [comment]
no it doesnt work bruh i compiled zcb.py

**Comment by ghost** [comment]
pls help me

**Comment by ghost** [comment]
where is the main.py?

**Comment by ghost** [comment]
pls give me the full source code

**Comment by zeopticz** [comment]
> pls give me the full source code

This repository already contains the full source code
Do you mind joining the discord? https://discord.gg/kGPAjmdpUX

**Comment by ghost** [comment]
i dont have discord sorry but i would want if i had

**Comment by zeopticz** [comment]
> i dont have discord sorry but i would want if i had

i already told you that you can use either pyinstaller or nuitka. it's a simple google search

**Comment by ghost** [comment]
i used py installer

**Comment by zeopticz** [comment]
> where is the main.py?

there is no main.py, zcb.py is the main file

**Comment by ghost** [comment]
huh?

**Comment by zeopticz** [comment]
> huh?

https://github.com/zeopticz/zcb-2.0/blob/master/src/zcb.py

**Comment by ghost** [comment]
it just closes after less than 2 seconds

**Comment by zeopticz** [comment]
> it just closes after less than 2 seconds

I don't think that's an issue with ZCB, can you please send the error message? Did you install all the dependencies correctly?

**Comment by ghost** [comment]
failed to execute scb i think it said

**Comment by zeopticz** [comment]
> failed to execute scb i think it said

The error message was "failed to execute scb i think it said"?

**Comment by ghost** [comment]
Error:
Traceback (most recent call last):
  File "zcb.py", line 4, in <module>
    from utils import *
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "utils.py", line 2, in <module>
    from pydub import AudioSegment
ModuleNotFoundError: No module named 'pydub'
[7232] Failed to execute script 'zcb' due to unhandled exception!

**Comment by zeopticz** [comment]
> Error: Traceback (most recent call last): File "zcb.py", line 4, in from utils import * File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module File "utils.py", line 2, in from pydub import AudioSegment ModuleNotFoundError: No module named 'pydub' [7232] Failed to execute script 'zcb' due to unhandled exception!

Have you tried installing `pydub`? Also, please use code blocks

**Comment by ghost** [comment]
no

**Comment by ghost** [comment]
ok installed

**Comment by zeopticz** [comment]
> no

Okay. Try installing `pydub` and other dependencies. You can do it like this (if you have `pip` installed on your system):
`pip install -r requirements.txt` in the `src` folder.

**Comment by ghost** [comment]
ok installed

**Comment by zeopticz** [comment]
> ok installed

I don't really care if you did it or not

**Comment by ghost** [comment]
"I DID!"

**Comment by ghost** [comment]
okay compiling with the requimerements installed

**Comment by ghost** [comment]
YESSSSSSSSSSSSSSSSSS IT WORKS!^!@^*327834890324782543789324789

**Comment by ghost** [comment]
can you give me best clicks that work with zcb

**Comment by ghost** [comment]
plssssssssss

**Comment by user100056** [comment]
please!!!!!!!!!11

**Comment by ghost** [comment]
Give me click pack that works with zcb

**Comment by zeopticz** [comment]
> Give me click pack that works with zcb

everything is in the discord. you can find clicks-example.zip on older releases.

**Comment by ghost** [comment]
pls give cdn discord link

**Comment by ghost** [comment]
i dont want to go though the stupid discord verification

**Comment by zeopticz** [comment]
> i dont want to go though the stupid discord verification

you don't have an email? Discord only needs your email for registration

**Comment by ghost** [comment]
well pls

**Comment by zeopticz** [comment]
> pls give cdn discord link

I can't just send you one link, there are several

**Comment by ghost** [comment]
send all of them ( ͡° ͜ʖ ͡°)

**Comment by ghost** [comment]
just kidding the best one you prefer

**Comment by zeopticz** [comment]
> just kidding the best one you prefer

I don't know, I never tried a single one

**Comment by ghost** [comment]
how much people have made?

**Comment by zeopticz** [comment]
> how much people have made?

I don't know, a lot?

**Comment by ghost** [comment]
is there called Kawaii clicks?

**Comment by ghost** [comment]
ok send me one you use

**Comment by zeopticz** [comment]
> ok send me one you use

https://github.com/zeopticz/zcb-2.0/releases/download/1.2/clicks-example.zip

**Comment by zeopticz** [comment]
> is there called Kawaii clicks?

No idea

**Comment by ghost** [comment]
KaiGuy uses it

**Comment by ghost** [comment]
wat is soft click

**Comment by zeopticz** [comment]
> wat is soft click

You can either smash or mouse or click it softly, when you're spamming it will output soft clicks instead of hard clicks.

**Comment by ghost** [comment]
rendering

**Comment by ghost** [comment]
slaughterhouse echo

**Comment by ghost** [comment]
120 fps

**Comment by ghost** [comment]
done

**Comment by zeopticz** [comment]
why are you sending so many messages under this issue?

**Comment by ghost** [comment]
idk lol

**Comment by zeopticz** [comment]
use the discord for that

**Comment by ghost** [comment]
pls no

**Comment by ghost** [comment]
rendering a replay with 1430 actions

**Comment by ghost** [comment]
wait what is non binary echo?

**Comment by ghost** [comment]
can you give me m4rk clicks that work with zcb?

**Comment by zeopticz** [comment]
> can you give me m4rk clicks that work with zcb?

No. Join the discord.

**Comment by ghost** [comment]
why?

**Comment by ghost** [comment]
pls givem me YOU use.

**Comment by zeopticz** [comment]
> pls givem me YOU use.

I already gave it to you. https://github.com/zeopticz/zcb-2.0/issues/3#issuecomment-1173095422

**Comment by user100056** [comment]
[my outcome.zip](https://github.com/zeopticz/zcb-2.0/files/9034959/my.outcome.zip)

**Comment by ghost** [comment]
also i found a 0 iq bug

**Comment by ghost** [comment]
with the zbc

**Comment by zeopticz** [comment]
> also i found a 0 iq bug

open a new issue if you want to report a bug.

**Comment by ghost** [comment]
done

**Comment by ghost** [comment]
look

**Comment by ghost** [comment]
are checking the bug?

**Comment by ghost** [comment]
if it doesnt happen tell me.

**Comment by ghost** [comment]
doesnt?

**Comment by ghost** [comment]
answer

**Comment by zeopticz** [comment]
> if it doesnt happen tell me.

I won't, I will just close the issue (https://github.com/zeopticz/zcb-2.0/issues/6). Stop spamming comments on this issue (https://github.com/zeopticz/zcb-2.0/issues/3)

**Comment by ghost** [comment]
ok sorry maybe that has to do something while compiling ok.

**Comment by zeopticz** [comment]
> ok sorry maybe that has to do something while compiling ok.

No, I did not test it yet.

**Comment by ghost** [comment]
:angry:

**Comment by ghost** [comment]
oh

**Comment by ghost** [comment]
also if its true, mark it as confirmed for people to know.

**Comment by ghost** [comment]
Also HOW DARE YOU REJECT MY FIRST ISSUE?!!?!?!?!

**Comment by zeopticz** [comment]
> also if its true, mark it as confirmed for people to know.

I don't have this label currently.

**Comment by zeopticz** [comment]
> Also HOW DARE YOU REJECT MY FIRST ISSUE?!!?!?!?!

I did not reject anything yet. Your issue (#6) is still open.

**Comment by ghost** [comment]
ok sorry bruh this issue has 100 commnts xd sorry

**Comment by user100056** [comment]
[1 action macro.zip](https://github.com/zeopticz/zcb-2.0/files/9034972/1.action.macro.zip)

**Comment by ghost** [comment]
test it with that

**Comment by zeopticz** [comment]
> [1 action macro.zip](https://github.com/zeopticz/zcb-2.0/files/9034972/1.action.macro.zip)

not related to this issue

**Comment by ghost** [comment]
oh yea also the first macro i rendered was named converted i choosed default soft click and choosed yes if make clicks more realistic on the second attempt i also choosed default soft click but choosed no to make clicks more realistic.

**Comment by ghost** [comment]
maybe also that has to do with issue

**Comment by zeopticz** [comment]
> oh yea also the first macro i rendered was named converted i choosed default soft click and choosed yes if make clicks more realistic on the second attempt i also choosed default soft click but choosed no to make clicks more realistic.

not related to this issue

**Comment by ghost** [comment]
is it true?

**Comment by zeopticz** [comment]
> is it true?

I don't know what you're talking about

**Comment by ghost** [comment]
above about the issue

**Comment by ghost** [comment]
ok i wont comment anything here anymore i will comment in Error while exporting issue.
