### ISSUE TITLE
Error while exporting

### ISSUE THREAD

**Issue by ghost** [zeopticz/zcb-2.0#6]
If you export click sound of a macro (you know what i mean) that has name that already is in the output folder it will fail while exporting. (Not while rendering)

**Comment by ghost** [comment]
Is the bug confirmed?

**Comment by zeopticz** [comment]
> Is the bug confirmed?

Not yet. I did not test it.

**Comment by ghost** [comment]
Why??

**Comment by ghost** [comment]
Oh yea question: what is best delay in ms softclicks?

**Comment by zeopticz** [comment]
> Why??

I'm currently busy doing other stuff

**Comment by ghost** [comment]
confirmed?

**Comment by user100056** [comment]
i joined your server username: user355
