### ISSUE TITLE
Clicks bug

### ISSUE THREAD

**Issue by ghost** [zeopticz/zcb-2.0#7]
Doesnt work with these click
[Oh my god.zip](https://github.com/zeopticz/zcb-2.0/files/9035058/Oh.my.god.zip)
it finishes rendering too quickly.

**Comment by zeopticz** [comment]
Can you post any error message/issue you're experiencing? Expected output? Steps to reproduce?

**Comment by user100056** [comment]
Why you cant do it yourself??

**Comment by ghost** [comment]
incorrect output

**Comment by zeopticz** [comment]
> Why you cant do it yourself??

I don't know how you did it. Please post the full error/issue you're experiencing, the expected output and the steps you did for me to reproduce the issue.

**Comment by ghost** [comment]
it renders 416 actions in 0.1 seconds using this click pack

**Comment by ghost** [comment]
and outcome is few seconds.

**Comment by zeopticz** [comment]
> it renders 416 actions in 0.1 seconds using this click pack

Can you send the replay? Can you exactly type out what buttons you clicked? Can you type the entire thing in one message? Does it produce any errors?

**Comment by ghost** [comment]
[Echo2.zip](https://github.com/zeopticz/zcb-2.0/files/9035238/Echo2.zip)
outcome
[nPesta Oh My.zip](https://github.com/zeopticz/zcb-2.0/files/9035241/nPesta.Oh.My.zip)
clicks

**Comment by ghost** [comment]
please fix this in 2.1 or maybe 2.0.5 or 2.0.1

**Comment by ghost** [comment]
will you release a minor update before 2.1 that has bug fixes?

**Comment by ghost** [comment]
you checking?

**Comment by zeopticz** [comment]
> please fix this in 2.1 or maybe 2.0.5 or 2.0.1

The releases tab is currently not updated with the newest commits. You can use the latest automatic builds on https://github.com/zeopticz/zcb-2.0/actions

**Comment by ghost** [comment]
but is it true?

**Comment by zeopticz** [comment]
> but is it true?

I did not reproduce your error yet. Please be more patient

**Comment by ghost** [comment]
also i cant download source code of other people's improvements

**Comment by zeopticz** [comment]
> also i cant download source code of other people's improvements

You can clone this repository or any other public fork of this.

**Comment by ghost** [comment]
please give me realistic clicks!
